# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/04_graphnn.ipynb (unless otherwise specified).

__all__ = []

# Internal Cell
from torch.nn import Linear
from torch_geometric.nn import GCNConv
from torch_geometric.data import Dataset, Data, DataLoader
from torch_geometric.utils import to_networkx